version: '2'
services:
  meteorapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ROOT_URL=http://site.com
      - MONGO_URL=mongodb://meteordb:27017/db
      - MONGO_OPLOG_URL=mongodb://oplogger:oplogger@meteordb:27017/local?authSource=admin
    restart: always
    links:
      - meteordb

  meteordb:
    build:
      context: ..
      dockerfile: docker/Dockerfile.db
    restart: always

