FROM alpine:edge
WORKDIR /home/mongodb

COPY ./docker /home/mongodb/docker/	

RUN adduser mongodb -h /home/mongodb -s /bin/sh -D

# prepare the folder where the db will be created
RUN	mkdir -p /data/db  && \
	chown -R mongodb:mongodb /data   && \
	chmod -R 666 /data   && \
	find /data -type d -exec chmod 744 {} \; 

# make sure all files are owned by user meteor and only have read/write permissions (except shell scrips that need to be executable)
RUN	chown -R mongodb:mongodb .  && \
	chmod -R 666 .  && \
	find . -type d -exec chmod 744 {} \;  && \
	chmod 766 docker/*.sh

# prepare access from external IP, and configure replica set (to enable OPLOG tailing in Meteor)
RUN	apk --update add --no-cache mongodb && \
	rm /usr/bin/mongoperf
	
USER mongodb 
RUN	mongod --fork --syslog  && \
	sleep 10  && \
	mongo admin --eval 'db.createUser({user: "oplogger", pwd: "oplogger", roles: [{role: "read", db: "local"}]})'  && \
	mongod --shutdown --dbpath /data/db

EXPOSE 27017

# Execute entrypoint as user meteor
ENTRYPOINT ["/home/mongodb/docker/db_entrypoint.sh"]
CMD []
